Save exchange rate hints to disk to use across all accounts
EdgeApp/edge-core-js pull request #359
Opened 2021-03-17 07:05 UTC by peachbits

2021-03-17 19:04 UTC, peachbits commented on src/core/root-reducer.js
> +  rateHintCache(state = DEFAULT_RATE_HINTS, action): EdgeRateHint[] {
empty array

2021-03-18 23:06 UTC, peachbits commented on src/core/exchange/exchange-pixie.js
> +          input.props.log.error('Update rateHintCache.txt error', error)
onError isn't available when doing the initial read but it was added to the write in gatherHints

2021-03-19 23:45 UTC, paullinator requested changes

2021-03-19 23:45 UTC, paullinator commented on src/core/root.js
> +        log.error('Create rateHintCache.txt failure', error.message)
This is a catastrophic error condition, throw the error

2021-03-19 23:45 UTC, paullinator commented on src/core/root.js
> +      log.error('Read rateHintCache.txt error', error.message)
This is a catastrophic error condition, throw the error

2021-03-19 23:45 UTC, paullinator commented on src/core/root.js
> +      log.error('Read rateHintCache.txt error', error.message)
or call `input.props.onError()`

2021-03-24 04:05 UTC, paullinator approved these changes

2021-03-24 04:05 UTC, merged