Allow plugins to fail to load
EdgeApp/edge-core-js pull request #467
Opened 2022-07-25 22:58 UTC by peachbits

This was tested by breaking a currency plugin on devices that don't support bigints. It does not blow up. The app loads normally without any mention of the broken plugin.

This has not been tested with other types of plugins like rates or swaps.

2022-07-26 18:06 UTC, swansontec requested changes
Nope! This is not the way.

You know how plugins have a factory function that takes the IO objects? We should add `| void` to the allowed return values of that function. That way, your `makePolkadotPlugin` can decide whether or not the browser is good to go, and then return `undefined` if it isn't happy. This is different from allowing plugins to crash, and then just ignoring the errors.

2022-07-26 18:17 UTC, peachbits commented
It is definitely a hack I just needed to get into QA so they test old androids. Your suggestion makes sense I'll look into it and update the PR

2022-07-27 01:51 UTC, swansontec requested changes

2022-07-27 01:51 UTC, swansontec commented on src/core/plugins/plugins-reducer.js
> +          delete out.init[pluginId]
This is Redux, so we can't just delete things. I think we can do `out.init = { ...out.init, [pluginId]: false }`, though.

2022-07-27 17:52 UTC, swansontec approved these changes

2022-07-27 18:41 UTC, merged